CFLAGS=-Wall -g -pthread
LDFLAGS=-lrt -pthread
LOADLIBES=-lrt

EXE=                   \
	exemple_01     \
	exemple_02     \
	exemple_03     \
	exemple_04     \
	exemple_05     \
	exemple_06     \
	exemple_07     \
	exemple_08     \

all: ${EXE}

clean:
	rm -f ${EXE} *.o *.gcno *.gcda



